version: '3.5'
services:
    my_django_service:
      container_name: my_django-container
      build:
        context: ./
        dockerfile: ./Dockerfile
      environment:
        PYTHONUNBUFFERED: 1
        TZ: Asia/Shanghai
#      command: uwsgi --ini etc-uwsgi.ini python manage.py runserver 0.0.0.0:8001
#      command: >
#        bash -c "
#                nohup python manage.py runserver 0.0.0.0:8001 >& uwsgi_out.log 2>&1 &
#                nohup celery --app=celery_tasks.celery worker -l INFO >& celery_out.log 2>&1
#                "
      command: >
        bash -c "
                 supervisord -c service_config/supervisord.conf &&
                 supervisorctl -c service_config/supervisord.conf start all
                "
#      command: >
#        bash -c "uwsgi --ini uwsgi.ini"
      restart: always
      volumes:
        - ../my_django_service:/app
        # (HOST:CONTAINER)
      ports:
        - "8001:8001"
        - "8000:8000"
        - "6379:6379"
        - "9001:9001"
        # (HOST:CONTAINER)
      networks:
        - proxy

    nginx:
      container_name: nginx-container
      build: ./nginx

      environment:
        TZ: Asia/Shanghai

      restart: always
      ports:
        - "8080:80"
      volumes:
        - ../my_django_service:/app
        - ./logs/nginx_service:/var/log/nginx
      depends_on:
        - my_django_service

      networks:
        - proxy

    logstash:
      container_name: logstash-container
      build:
        context: logstash_service/
      volumes:
        - ../my_django_service/logs/nginx_service:/app/logs
        - ./logstash_service/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash_service/pipeline:/usr/share/logstash/pipeline:ro
      ports:
        - "5000:5000"
        - "12201:12201/udp"
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        TZ: Asia/Shanghai
      networks:
        - proxy
      depends_on:
        - nginx

volumes:
    api_data:

networks:
  proxy:
    name: my_network
