# Generated by Django 2.2.3 on 2023-01-06 07:34

import apps.utils.common_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFileManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('file_id', models.CharField(default=apps.utils.common_models.gen_id, help_text='文件ID', max_length=255, verbose_name='文件ID')),
                ('file_name', models.CharField(blank=True, help_text='文件名称', max_length=255, null=True, verbose_name='文件名称')),
                ('file_type', models.CharField(blank=True, help_text='文件类型', max_length=255, null=True, verbose_name='文件类型')),
                ('file_size', models.CharField(blank=True, help_text='文件大小', max_length=64, null=True, verbose_name='文件大小')),
                ('address', models.CharField(blank=True, help_text='存储位置', max_length=64, null=True, verbose_name='存储位置')),
                ('source', models.CharField(blank=True, help_text='文件来源', max_length=16, null=True, verbose_name='文件来源')),
                ('is_success', models.BooleanField(default=0, verbose_name='是否上传成功')),
            ],
            options={
                'verbose_name': '文件管理表',
                'verbose_name_plural': '文件管理表',
                'db_table': 'system_file_manage',
            },
        ),
    ]
