# Generated by Django 2.2.3 on 2023-01-31 06:15

import apps.utils.common_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCommonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '有效'), (1, '临时记录'), (9, '删除')], db_index=True, default=0, verbose_name='记录状态')),
                ('config_key', models.CharField(default=apps.utils.common_models.gen_id, help_text='配置ID', max_length=255, verbose_name='配置ID')),
                ('config_name', models.CharField(blank=True, help_text='配置名称', max_length=255, null=True, verbose_name='配置名称')),
                ('config_type', models.CharField(blank=True, help_text='配置类型', max_length=255, null=True, verbose_name='配置类型')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('config_value', models.TextField(default='', verbose_name='值')),
                ('remark', models.TextField(default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '系统公共配置管理表',
                'verbose_name_plural': '系统公共配置管理表',
                'db_table': 'system_common_config',
            },
        ),
    ]
