# Generated by Django 2.2.3 on 2023-02-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userwebaccountmanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(blank=True, help_text='书名', max_length=255, null=True, verbose_name='书名')),
                ('author', models.CharField(blank=True, help_text='作者', max_length=255, null=True, verbose_name='作者')),
                ('intro', models.CharField(blank=True, help_text='介绍', max_length=500, null=True, verbose_name='介绍')),
                ('detail_url', models.CharField(blank=True, help_text='详情URL', max_length=255, null=True, verbose_name='详情URL')),
                ('source', models.CharField(blank=True, help_text='来源', max_length=255, null=True, verbose_name='来源')),
            ],
            options={
                'verbose_name': '书库',
                'verbose_name_plural': '书库',
                'db_table': 'app_user_book_manage',
            },
        ),
    ]
