# Generated by Django 2.2.3 on 2023-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_bookinfomanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfomanage',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterUniqueTogether(
            name='bookinfomanage',
            unique_together={('book', 'source', 'author')},
        ),
    ]
